### ISSUE TITLE
pandocomatic with multiple input files (contatenated)

### ISSUE THREAD

**Issue by agusmba** [htdebeer/pandocomatic#65]
When you invoke pandoc with multiple input files, it concatenates them and converts them as if they were a single input file.

Reading the docs and trying pandocomatic with multiple `-i` arguments, it seems that this is not supported by pandocomatic. (Note that directory conversion converts on an individual file basis, not as a whole).

Is this something that could be supported?

Thanks!

**Comment by htdebeer** [comment]
It is something we should look into a bit further before we can make a decision if it can be supported or not. If we're not careful about implementing this feature, pandocomatic's behavior might become a bit confusing with regards to the input files.

To be honest, it already is a bit confusing because you can specify the output file in a template as well as on the command-line.

At the moment, pandocomatic converts one input file to one output file or one input directory to one output directory. The proposed change suggests allowing multiple input files to generate one output file. 

I do have a couple of questions I'd like to discuss:

1. Should we also support multiple input directories? Should they then be generated into one output directory? This could be a handy feature to generate a website from a couple of different directories, maybe even using some directories in multiple generated websites.
2. Should we also support multiple output files / output directories? If so, how do we know which input files/directories should be converted to which output files/directories? For example, in `pandocomatic -i 1.md -i 2.md -o out1.tex -i 3.md -o out2.docx`, should the files `1.md` and `2.md` be converted to `out1.tex` and `3.md` to `out2.docx`?
3. Should we support multiple `-i/--input` options? Or only allow multiple input files when they are at the end of the pandocomatic invocation like in `pandocomatic -c config.yaml 1.md 2.md 3.md`?
4. What do we do with input files that also explicitly specify an output file in the YAML metadata? Should they still be concatenated into one output file? Should they still be converted into the output file specified in the YAML metadata? 
5. Should we support using an input directory and converting that to one output file by concatenating all files in the input directory? And if so, would we want to support this in templates as well, for example with a pattern to describe what files in the directory are to be concatenated and maybe add an option `concatenate` for `pandocomatic.yaml` template files in directories?

Comments and ideas welcome.

**Comment by agusmba** [comment]
I see things can get complicated pretty quickly.

I would try to approach this in a simple way. Start with basic and "simple" functionality and iterate from this.

My first step proposal would be: *pandocomatic should parse the yaml metadata from the included individual files, and merge them (for instance making sure only one output file remains in the final configuration), then pass all the files to pandoc for processing*

> Should we also support multiple input directories? Should they then be generated into one output directory?

I think supporting multiple directories is a different feature, as when you enter a directory, pandocomatic uses a file-by-file conversion (unless you where thinking about using a switch to change this behavior). If you are keen on implementing this, the feature overload of `-i` with different behavior depending on using directories or files, could indeed be a bit confusing.

> Should we also support multiple output files / output directories? If so, how do we know which input files/directories should be converted to which output files/directories? 

Regarding input files, I would try to mimic pandoc's behavior in that pandocomatic should parse the pandocomatic-yaml metadata from the included files, and merge them (for instance making sure only one output file remains in the final configuration), then pass all the files to pandoc for processing.

Regarding multiple output files/directories, I'd steer away from this atm. See my comments above. Multiple input files should work as in pandoc currently, merging the pandocomatic-yaml configuration into a single sensible config, and multiple input directories, could go to the same output directory (not sure about this last one as you seem to have a clearer use case for it than me)

> Should we support multiple -i/--input options? Or only allow multiple input files when they are at the end of the pandocomatic invocation

Either way is fine, although see my comments above regarding the overloading of `-i`

> What do we do with input files that also explicitly specify an output file in the YAML metadata?

I'd use the same approach as today, regarding command-line precedence vs YAML metadata, with the addition that there is a YAML-metadata merge step, where pandocomatic retrieves all YAML metadata from multiple input files and merges them in a sensible way. Thus only one output file should be defined in the end.

> Should we support using an input directory and converting that to one output file by concatenating all files in the input directory? 

This is yet another new feature, completely different from what pandocomatic does currently. It could be useful, but I'd not tackle this in a first step. If implemented though, either a flag-switch or a completely different option should be used, in order not to confuse the current `-i` behavior.

Thank you for being open to discussing this!

**Comment by htdebeer** [comment]
Thanks for your feed-back. Starting out simple is always good advice, but design choices we now make will have an effect later on, particularly for related functionality.

You suggest merging all the YAML metadata from all the individual files into a single one for the concatenated file. This makes sense, but we have to take care when the same metadata is being used in multiple files. The most obvious solution is to merge those properties that can be merged and to overwrite the others, giving precedence to the last occurrence of the property. Properties that can be merged are metadata properties and properties that can occur multiple times such as `--include-in-header` and `--variable`. 

Then there are some properties, like `--output`, `--template` or `--data-dir` where merging is not an option and taking the last occurrence of an property could result in invalid metadata. For example, assuming input file `1.md` with metadata `output: out.pdf`, `to: latex`, and `pdf-engine: lualatex` and input file `2.md` with metadata `to: html`. This would result in invoking pandoc like: `pandoc --from markdown --to html --output out.pdf --pdf-engine=lualatex 1.md 2.md`. That does not seem right.

We need to find a heuristic for merging the metadata when concatenating input files. Possible heuristics:

- Ignore all metadata in the input files, use a separate metadata file instead
- Use the metadata in the first input file, ignore the metadata in the rest of the files.
- The same, but with the last file
- Specify the behavior of all pandoc options with regard to merging, ignoring, or overwriting. I am not sure we can make a specification that works for all situations, though.

The simplest option would be to allow only one input file containing all the metadata to use, but add a property to the internal template of the input file describing the files to concatenate. For example:

```yaml
pandocomatic_:
  pandoc:
    from: markdown
    to: html
  concatenate:
    - 1.md
    - 2.md
```

The metadata in `1.md` and `2.md` would then be ignored. Would a solution like this work for you? Or do you have a specific reason why you'd like to specify the files to concatenate on the command-line?

(As an aside, I use the filter [`::paru::insert``](https://github.com/htdebeer/paru-filter-collection) to "include" other files into my markdown files. This is somewhat similar to the simple heuristic proposed before, but it allows finer control over how things are included)

**Comment by agusmba** [comment]
Of the possible heuristics, I think the one that makes more sense is to use the pandocomatic-yaml config found in the first file. This would work with a separate yaml file (which users would put first), or with a main first input file plus additional chapters in additional files.

Regarding how to tell pandocomatic about multiple input files, be it command line or via the `concatenate` option, wouldn't you get both if you implement the `concatenate` option? (which could be defined in the input file metadata but also in the commandline, right?) I don't feel strongly about any option, but

> The simplest option would be to allow only one input file containing all the metadata to use, but add a property to the internal template of the input file describing the files to concatenate.

your proposal sounds great!

Thanks for the paru link. I guess I could use it as a workaround, but it would mean adding an additional filter even if I were to use pandoc directly (I try to support pandocomatic but also direct pandoc invocations when writing docs). So I'd still prefer if pandocomatic supported passing multiple input files to pandoc.

**Comment by htdebeer** [comment]
You're right, using a template property or multiple input files on the command-line is largely the same thing anyway. I will implement this. 

The user can specify one or more input files and only the `pandocomatic_` metadata property in the first file will be used. Pandocomatic metadata in all other files will be ignored.

The behavior for directories is not yet clear to me, so either it is not supported in the first iteration or I will define this behavior whilst I am implementing this feature for files.

Would you like to be able to use a [glob pattern](https://en.wikipedia.org/wiki/Glob_%28programming%29) to specify one or more input files?

**Comment by agusmba** [comment]
Thanks!

Sounds like a plan!

My current use case is quite simple, so I don't personally need glob pattern now, so I'll leave it up to you to weight the benefits vs the difficulty of supporting that.

**Comment by htdebeer** [comment]
I have created a first working implementation in a [separate branch](https://github.com/htdebeer/pandocomatic/tree/support_multiple_input_files). It feels a bit tacked-on though, so I'll take the time to redesign and develop a more robust implementation to handle the various input scenarios.

**Comment by agusmba** [comment]
Thank you!
Is there an easy way to install it locally so I can test it? (I didn't see a new .gem in the releases folder)

**Comment by htdebeer** [comment]
I'll create an α-version of pandocomatic as soon as I clean-up the code a bit. I've rewrote the solution I had into something more general and took the opportunity to rework the code-base to better separate concerns between the various parts of pandocomatic. The only issue I still have is if and how to determine if the multiple input files are pandoc markdown files or some other input format. If the former, I have to strip the metadata. If the latter, I should not.

Anyway, there is a way to test the latest code for I have added a `pandocomatic.rb` script to the `test` directory that uses the code in the `lib` directory rather than the installed pandocomatic version. If you check out the branch mentioned above then the following should work:

```bash
cd /dir/you/checked/out/the/branch
test/pandocomatic.rb -i 1.md -i 2.md -o out.html
```

You can also use extra input parameters while invoking pandocomatic:

```bash
test/pandocomatic.rb -o out.html  1.md 2.md
```

You **cannot** mix these two forms of specifying the input, though.

**Comment by agusmba** [comment]
> The only issue I still have is if and how to determine if the multiple input files are pandoc markdown files or some other input format. If the former, I have to strip the metadata

I'd try to let pandoc handle that. Supposedly pandoc does its own merge of all the input files, so pandocomatic could leverage that.
The only thing pandocomatic should do is scan the first input file for a pandocomatic section in the metadata (if that's the chosen solution).

**Comment by htdebeer** [comment]
I've pushed pandocomatic version 0.2.5.0.alpha to Rubygems. You can test this version for the new feature with multiple inputs. At the moment I concatenate all the input files and remove the metadata from all the input files but the first. Comments welcome.

**Comment by agusmba** [comment]
Mmmm, trying the new version:

```
$ gem install pandocomatic --pre
Fetching: paru-0.3.2.0.gem (100%)
Successfully installed paru-0.3.2.0
Fetching: optimist-3.0.0.gem (100%)
Successfully installed optimist-3.0.0
Fetching: pandocomatic-0.2.5.0.alpha.gem (100%)
Successfully installed pandocomatic-0.2.5.0.alpha
Parsing documentation for paru-0.3.2.0
Installing ri documentation for paru-0.3.2.0
Parsing documentation for optimist-3.0.0
Installing ri documentation for optimist-3.0.0
Parsing documentation for pandocomatic-0.2.5.0.alpha
Installing ri documentation for pandocomatic-0.2.5.0.alpha
Done installing documentation for paru, optimist, pandocomatic after 7 seconds
3 gems installed

$ pandocomatic --data-dir=res -b -i src/document.md -o build/document.docx
An unexpected error has occurred. You can report this bug via https://github.com/htdebeer/pandocomatic/issues/new.
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/pandocomatic-0.2.5.0.alpha/lib/pandocomatic/configuration.rb:377:in `block in set_destination': undefined method `has_key?' for nil:NilClass (NoMethodError)
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/pandocomatic-0.2.5.0.alpha/lib/pandocomatic/configuration.rb:397:in `set_destination'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/pandocomatic-0.2.5.0.alpha/lib/pandocomatic/command/convert_file_command.rb:77:in `initialize'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/pandocomatic-0.2.5.0.alpha/lib/pandocomatic/command/convert_file_multiple_command.rb:60:in `new'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/pandocomatic-0.2.5.0.alpha/lib/pandocomatic/command/convert_file_multiple_command.rb:60:in `block in initialize'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/pandocomatic-0.2.5.0.alpha/lib/pandocomatic/command/convert_file_multiple_command.rb:57:in `each'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/pandocomatic-0.2.5.0.alpha/lib/pandocomatic/command/convert_file_multiple_command.rb:57:in `initialize'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/pandocomatic-0.2.5.0.alpha/lib/pandocomatic/pandocomatic.rb:77:in `new'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/pandocomatic-0.2.5.0.alpha/lib/pandocomatic/pandocomatic.rb:77:in `run'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/pandocomatic-0.2.5.0.alpha/bin/pandocomatic:3:in `<top (required)>'
        from C:/Ruby24-x64/bin/pandocomatic:23:in `load'
        from C:/Ruby24-x64/bin/pandocomatic:23:in `<main>'
```

**Comment by agusmba** [comment]
This seems to also be broken in 2.4.1, I need to find which working version I had before...

**Comment by agusmba** [comment]
Ok, it seems the last version that works in my box is 0.2.0.5, something changed in 0.2.1 that breaks in my box.

**Comment by agusmba** [comment]
sorry, let me open a different issue for this

**Comment by agusmba** [comment]
ok, after the workaround for #66

pandocomatic works on a single file input, but not if I duplicate the frontmatter into a different document:

```
$ pandocomatic --data-dir=res -b -i src/frontmatter.md -i src/document.md -o build/document.docx
An unexpected error has occurred. You can report this bug via https://github.com/htdebeer/pandocomatic/issues/new.
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/pandocomatic-0.2.5.0.alpha/lib/pandocomatic/pandocomatic.rb:111:in `ensure in run': undefined method `clean_up!' for nil:NilClass (NoMethodError)
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/pandocomatic-0.2.5.0.alpha/lib/pandocomatic/pandocomatic.rb:111:in `run'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/pandocomatic-0.2.5.0.alpha/bin/pandocomatic:3:in `<top (required)>'
        from C:/Ruby24-x64/bin/pandocomatic:23:in `load'
        from C:/Ruby24-x64/bin/pandocomatic:23:in `<main>'
```

**Comment by agusmba** [comment]
BTW:

> At the moment I concatenate all the input files and remove the metadata from all the input files but the first.

Is this necessary? Maybe it's a good thing, I'm not sure, but since pandoc supposedly does the same merge, wouldn't it make sense to let pandoc deal with multiple metadata definitions?

Wouldn't it be easier to only read the `pandocomatic_` block from the first file and simply merge the input files for pandoc? (I'm assuming pandoc won't choke on this merge and will work as if multiple input files were passed directly to it).

**Comment by agusmba** [comment]
A simple document with the problem (save to `pandocomatic-issue-65.md`):

``````markdown
---
title: "Testing Pandocomatic #65"
author: agusmba
pandocomatic_:
    pandoc:
        to: docx
        standalone: true
...

This is a test. Compile with:

    pandocomatic -i pandocomatic-issue-65.md -o pandocomatic-issue-65.docx

It works.

Now copy and paste the frontmatter to `frontmatter.md` and do:

    pandocomatic -i frontmatter.md -i pandocomatic-issue-65.md -o pandocomatic-issue-65.docx

it should work but we get:

```
$ pandocomatic -i frontmatter.md -i pandocomatic-issue-65.md -o pandocomatic-issue-65.docx
An unexpected error has occurred. You can report this bug via https://github.com/htdebeer/pandocomatic/issues/new.
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/pandocomatic-0.2.5.0.alpha/lib/pandocomatic/pandocomatic.rb:111:in `ensure in run': undefined method `clean_up!' for nil:NilClass (NoMethodError)
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/pandocomatic-0.2.5.0.alpha/lib/pandocomatic/pandocomatic.rb:111:in `run'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/pandocomatic-0.2.5.0.alpha/bin/pandocomatic:3:in `<top (required)>'
        from C:/Ruby24-x64/bin/pandocomatic:23:in `load'
        from C:/Ruby24-x64/bin/pandocomatic:23:in `<main>'
```
``````

Here are the files in case you want to skip creating the documents: 
[pandocomatic-issue-65.zip](https://github.com/htdebeer/pandocomatic/files/2953075/pandocomatic-issue-65.zip)

**Comment by htdebeer** [comment]
> BTW:
> 
> > At the moment I concatenate all the input files and remove the metadata from all the input files but the first.
> 
> Is this necessary? Maybe it's a good thing, I'm not sure, but since pandoc supposedly does the same merge, wouldn't it make sense to let pandoc deal with multiple metadata definitions?
> 
> Wouldn't it be easier to only read the `pandocomatic_` block from the first file and simply merge the input files for pandoc? (I'm assuming pandoc won't choke on this merge and will work as if multiple input files were passed directly to it).

It would be easier but for the fact that pandocomatic also has a *startup* and a *preprocessor* phase before actually calling pandoc. I do not know if these earlier phases make sense when processing each input file separately as compared to one concatenated file. 

If we start preprocessing files separately, we need to introduce more control about what files to process. I'll have to think about the consequences of concatenating versus having pandoc handle mutliple input files a bit more. 

First, however, I'll look into #66.

**Comment by htdebeer** [comment]
I've pushed pandocomatic-0.2.5.betaa (yes, with two "a"s because I forgot to add in the fixes in the master branch into the feature branch). Has the issue with multiple inputs disappeared?

**Comment by agusmba** [comment]
Hi, sorry I was out of town for the weekend.

I tested the new version, but it still doesn't work:

```
$ gem uninstall pandocomatic
$ gem install pandocomatic --pre
Fetching: pandocomatic-0.2.5.0.betaa.gem (100%)
Successfully installed pandocomatic-0.2.5.0.betaa
Parsing documentation for pandocomatic-0.2.5.0.betaa
Installing ri documentation for pandocomatic-0.2.5.0.betaa
Done installing documentation for pandocomatic after 3 seconds
1 gem installed

$ pandocomatic -i pandocomatic-issue-65.md -o pandocomatic-issue-65.docx
Pandocomatic needed 0.3 seconds to convert 'D:/.../pandocomatic-issue-65.md' to 'pandocomatic-issue-65.docx'.

$ pandocomatic -i frontmatter.md  -i pandocomatic-issue-65.md -o pandocomatic-issue-65.docx
An unexpected error has occurred. You can report this bug via https://github.com/htdebeer/pandocomatic/issues/new.
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/pandocomatic-0.2.5.0.betaa/lib/pandocomatic/pandocomatic.rb:111:in `ensure in run': undefined method `clean_up!' for nil:NilClass (NoMethodError)
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/pandocomatic-0.2.5.0.betaa/lib/pandocomatic/pandocomatic.rb:111:in `run'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/pandocomatic-0.2.5.0.betaa/bin/pandocomatic:3:in `<top (required)>'
        from C:/Ruby24-x64/bin/pandocomatic:23:in `load'
        from C:/Ruby24-x64/bin/pandocomatic:23:in `<main>'
```

**Comment by htdebeer** [comment]
And it looks like the same issue. That looks like that particular file is not updated / has not been included in the gem somehow. I'll look into it further.

**Comment by htdebeer** [comment]
I've tried your latest scenario, but it seems to be working on my linux machine with ruby 2.6. When I run it with ruby 2.4 on the same machine it does show the error. It looks like I've used some ruby feature that has been introduced after 2.4.0. However, the error does not show up when I use ruby version 2.4.5.

I'll try to figure out which changes before 2.4.5 might cause the issue and try to fix it. If all else fails, I can always require ruby >= 2.4.5. I am not sure how many users I'd inconvenience with that though.

**Comment by htdebeer** [comment]
I've narrowed down the ruby version that "solved" this issue: [2.4.4](https://www.ruby-lang.org/en/news/2018/03/28/ruby-2-4-4-released/). However, that version does seem to be a bug fix and security update, so the issue could be a ruby bug rather than a pandocomatic bug.

Maybe it is best to require ruby 2.4.4 for pandocomatic 0.2.5.0?

**Comment by agusmba** [comment]
Requiring ruby 2.4.4 sounds fair.

I only installed ruby in order to use pandocomatic anyway :wink: 

Even though 2.4.4 would be enough, I'll upgrade to ruby 2.6 if that's what you're using.

Thanks for getting to the bottom of this!

**Comment by agusmba** [comment]
I was afraid regarding your previous comment

> At the moment I concatenate all the input files and remove the metadata from all the input files but the first.

However I see that pandoc is actually receiving the yaml metadata from all files, which is great

But it feels as if pandocomatic is reading the configuration from the last input file instead of the first (pandoc seems to receive the content in the right order though).

I have added the `toc: true` option to the pandocomatic config in `frontmatter.md`

Howerver it only works if I switch the order of the input files:

    $ pandocomatic -i pandocomatic-issue-65.md -i frontmatter.md  -o pandocomatic-issue-65.docx

**Comment by htdebeer** [comment]
That's not good. Thanks for noticing!

I'll reverse the order and start rewriting the documentation a bit. After that I either publish another beta or if everything else seems okay, the final version.

**Comment by htdebeer** [comment]
I've uploaded a new beta, version "c". I fixed the order issue you had and I also improved the reporting of converting multiple input files. I have not yet been able to reproduce the issue with the superfluous temporary file "D".

Can you test if these issues are gone on your end?

**Comment by iandol** [comment]
Just to say about the minimum version, macOS comes with ruby 2.3.7 by default, and this simplifies the use of pandocomatic for macOS users as they don't need to install Ruby at all. Will pandocomatic fail to run, or only not process multiple files?

**Comment by htdebeer** [comment]
Ar you sure that they still use Ruby 2.3.7? [Ruby 2.3.x will reach its end-of-life at the end of March 2019](https://www.ruby-lang.org/en/downloads/branches/).

Do note that the latest paru version expects at least Ruby 2.4. The current version of pandocomatic does require the latest version of paru (0.3.2). Does this mean that MacOSx users already cannot install pandocomatic (0.2.4.2, let alone 0.2.5)?

Anyway, the current working version of pandocomatic on their MacOSx system should keep working like it used before. They will just be unable to install the latest version until they upgrade their system to a branch that is not end-of-life.

**Comment by iandol** [comment]
Apple are very conservative and maintain their own build of all the tools that come with macOS, so yes as of the latest macOS, Ruby is at 2.3.7.

```bash
❯ /usr/bin/ruby -v
ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
```

If Paru already requires 2.4 then it is probably already broken yes. I use rbenv to install ruby, but most users of my scrivener workflow just stick to the ruby that comes with macOS. I will change the advice I give to them, and suggest they upgrade via rbenv/homebrew...

**Comment by agusmba** [comment]
This is strange, I uninstalled pandocomatic gem, and installed the latest one, but I get the `undefined method` error again (I had upgraded to ruby 2.4.5 last week):

```
$ gem uninstall pandocomatic
$ gem install pandocomatic --pre
$ ruby --version
ruby 2.4.5p335 (2018-10-18 revision 65137) [x64-mingw32]

$ pandocomatic -i frontmatter.md  -i pandocomatic-issue-65.md -o ../../../build/pandocomatic-issue-65.docx
An unexpected error has occurred. You can report this bug via https://github.com/htdebeer/pandocomatic/issues/new.
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/pandocomatic-0.2.5.0.betac/lib/pandocomatic/pandocomatic.rb:111:in `ensure in run': und
efined method `clean_up!' for nil:NilClass (NoMethodError)
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/pandocomatic-0.2.5.0.betac/lib/pandocomatic/pandocomatic.rb:111:in `run'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/pandocomatic-0.2.5.0.betac/bin/pandocomatic:3:in `<top (required)>'
        from C:/Ruby24-x64/bin/pandocomatic:23:in `load'
        from C:/Ruby24-x64/bin/pandocomatic:23:in `<main>'
```

**Comment by agusmba** [comment]
I upgraded my ruby to v2.6.1 and tested again.

Now the ordering is correct, however the pandoc metadata in subsequent files is not taken into account, which I think is undesirable, as it diverges from what `pandoc -i file1.md -i file2.md` does.

I think it's ok if pandocomatic only reads the pandocomatic section of the first file, but it shouldn't strip the yaml blocks from subsequent files, just concatenate it all (adding a new line [like pandoc does](https://pandoc.org/MANUAL.html#using-pandoc)) and let pandoc deal with it.

**Comment by agusmba** [comment]
BTW the "D" file still appears with ruby 2.6.1 and pandocomatic betac

**Comment by htdebeer** [comment]
This feature seems to become more and more problematic. The underlying issue is that in the current solution pandocomatic is overriding part of the behavior pandoc itself: concatenating the files beforehand. That was the quickest way to build this feature, but apparently not the best way.

I'll look into rewriting the feature where pandoc is tasked with concatenating the files like it is used to. This will take a bit longer, though, but in the long run this particular feature and pandocomatic in general will be better for it.

One of the main things to look out for is how to handle multiple input files in a preprocessor:
- The actual input file needs to be preprocessed, not a pandoc processed one.
- A preprocessor can change the input files, so these changed files need to be pushed through pandoc on STDIN (or use a separate temporary file)

**Comment by agusmba** [comment]
> This feature seems to become more and more problematic.

Yeah, sorry about that. I really appreciate all the effort you put into pandocomatic.

> I'll look into rewriting the feature where pandoc is tasked with concatenating the files like it is used to. This will take a bit longer, though, but in the long run this particular feature and pandocomatic in general will be better for it.

Indeed, this would be the future-proof solution, since it would allow pandocomatic (and filters) to behave as pre-processor for all input files, however I think your current solution is quite usable at the moment (better if you remove the "stripping" part :wink: ).

I'm currently using (and loving) pandocomatic on a daily basis, and this issue is not a showstopper, so please don't feel any kind of pressure at all.

**Comment by htdebeer** [comment]
Don't worry about pressure; working on pandocomatic is sort of a hobby, although I cannot spend as much time on it as I'd like. 

Anyway, my conclusion for this issue is that we cannot let pandoc do the concatenation on its own because we need to preprocess all input files in pandocomatic. That means that we either 
- have to preprocess each file separately into temporary files then then let pandoc concatenate these temporary files, or
- we let pandocomatic concatenates all the files first, which are preprocessed and pushed through pandoc via STDIN.

My preference would be the latter option because it will have less overhead.

I can also stop with removing metadata from multiple input files and task the user with not mixing problematic pandocomatic metadata in the multiple input files. That would solve some of the issues you reported and will be more robust over-all.

**Comment by htdebeer** [comment]
I've created a new beta version (pandocomatic-0.2.5.0.betad.gem). In this version no metadata is stripped and a warning is given when the `pandocomatic_` property does occur more than once in the input.

With respect to the temporary file issue, it does not happen on my linux system. It still does on yours?

Maybe it is something related to Windows? According to the [documentation](https://ruby-doc.org/stdlib-2.6.2/libdoc/tempfile/rdoc/Tempfile.html) temporary files should be removed automatically even if my call to `unlink` does not work somehow.

**Comment by agusmba** [comment]
Thank you!

It all seems to work as you describe, although I'm not sure about selecting the last occurrence of `pandocomatic_` instead of the first (which is what pandoc does whith metadata clashes in yaml blocks)

From Pandoc's manual:

> The metadata fields will be combined through a left-biased union: if two metadata blocks attempt to set the same field, the value from the first block will be taken.

I agree that this shouldn't be an issue since normally you'll only have the `pandocomatic_` block in one file, but still for alignment with pandoc, if it's not too troublesome to use the first occurrence I'd change it (if it's not too easy, it should be ok as it is).

Regarding the temp file, it's still happening. In order to narrow down the culprit, I purposefully created the `D` file with read only access, and thankfully pandocomatic broke:

```
$ pandocomatic -i frontmatter.md -i pandocomatic-issue-65.md -o ../../../build/pandocomatic-issue-65.docx
An unexpected error has occurred. You can report this bug via https://github.com/htdebeer/pandocomatic/issues/new.
Traceback (most recent call last):
        16: from D:/Ruby26-x64/bin/pandocomatic:23:in `<main>'
        15: from D:/Ruby26-x64/bin/pandocomatic:23:in `load'
        14: from D:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/pandocomatic-0.2.5.0.betad/bin/pandocomatic:3:in `<top (required)>'
        13: from D:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/pandocomatic-0.2.5.0.betad/lib/pandocomatic/pandocomatic.rb:58:in `run'
        12: from D:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/pandocomatic-0.2.5.0.betad/lib/pandocomatic/cli.rb:42:in `parse'
        11: from D:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/pandocomatic-0.2.5.0.betad/lib/pandocomatic/cli.rb:145:in `parse_options'
        10: from D:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/pandocomatic-0.2.5.0.betad/lib/pandocomatic/cli.rb:145:in `new'
         9: from D:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/pandocomatic-0.2.5.0.betad/lib/pandocomatic/configuration.rb:80:in `initialize'
         8: from D:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/pandocomatic-0.2.5.0.betad/lib/pandocomatic/configuration.rb:80:in `new'
         7: from D:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/pandocomatic-0.2.5.0.betad/lib/pandocomatic/multiple_files_input.rb:34:in `initialize'
         6: from D:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/pandocomatic-0.2.5.0.betad/lib/pandocomatic/multiple_files_input.rb:84:in `create_temp_file'
         5: from D:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/pandocomatic-0.2.5.0.betad/lib/pandocomatic/multiple_files_input.rb:84:in `new'
         4: from D:/Ruby26-x64/lib/ruby/2.6.0/tempfile.rb:131:in `initialize'
         3: from D:/Ruby26-x64/lib/ruby/2.6.0/tmpdir.rb:135:in `create'
         2: from D:/Ruby26-x64/lib/ruby/2.6.0/tempfile.rb:133:in `block in initialize'
         1: from D:/Ruby26-x64/lib/ruby/2.6.0/tempfile.rb:133:in `open'
D:/Ruby26-x64/lib/ruby/2.6.0/tempfile.rb:133:in `initialize': Permission denied @ rb_sysopen - D:/docs/pandoc/src/issues/pandocomatic-issue-65/D:docspandocsrcissuespandocomatic-issue-65frontmatter.md20190329-7252-1ogrg5d (Errno::EACCES)
```

The name of the temp file looks strange, somewhat duplicated with the last part mangling the directory separators. The second `:` is what's probably creating the `D` (since files cannot have `:` in the name) and thus preventing it's deletion if pandocomatic tries to use the non-existing full name.

Does that make sense?

**Comment by agusmba** [comment]
The issue is probably in https://github.com/htdebeer/pandocomatic/blob/af7da87743ad4c54649cd27f0a01fb6c77f943cb/lib/pandocomatic/multiple_files_input.rb#L84

`@input_files.first` seems to include the whole absolute path and it probably should be just the name of the file (or simply `pandocomatic` since that parameter is the base name of the temp file)

**Comment by htdebeer** [comment]
Thanks for the fix!

It should not be too difficult to use the first `pandocomatic_` block and ignore the rest rather than the other way around. Although the latter behavior is what Ruby's YAML parser is doing when presented with a YAML document containing the same property multiple times. However, as I am mining pandoc documents for metadata blocks anyway, I can stop mining once I've found a block with a `pandocomatic_` property. I'll keep the warning that multiple `pandocomatic_` properties have been found, though.

Do note that if a user would use the `pandocomatic_` property twice in one metadata block, the last occurrence is still the one being used because that's how YAML works. 

From the following document the first `pandocomatic_` property has precedence, so the output format is `html`.

```pandoc
---
title: My document with two separate metadata blocks
pandocomatic_:
  pandoc:
    from: markdown
    to: html
...

This is a long text and a couple of pages in I have another metadata block

---
pandocomatic_:
  pandoc:
    to: tex
...

And so on
```

However, in the following document, the output format will be `tex` and the `toc` option will be `false`:

```pandoc
---
pandocomatic_:
  pandoc:
    from: markdown
    to: html
    toc: true
title: My document with only one metadata block
pandocomatic_:
  pandoc:
    to: tex
...

This document has content...
```

Having the same property twice in one YAML document does not make sense.

**Comment by agusmba** [comment]
Thanks!

> However, as I am mining pandoc documents for metadata blocks anyway, I can stop mining once I've found a block with a pandocomatic_ property. [...]

That would be great!

> Do note that if a user would use the pandocomatic_ property twice in one metadata block, the last occurrence is still the one being used because that's how YAML works.
> Having the same property twice in one YAML document does not make sense.

I agree, this wouldn't make sense.

**Comment by htdebeer** [comment]
I've created a new beta version (pandocomatic-0.2.5.0.betae.gem) with the proposed changes. I still have to update the warning message when multiple YAML blocks with pandocomatic properties are encountered, but that's for the official release.

**Comment by agusmba** [comment]
It's working great on my end.
Thank you!
